application:
  debug: false
  admin_discord_id: 0

logging:
  discord_log_webhook: ""
  discord_status_webhook: ""

secret:
  discord:
    bot_token: ""
  fazbot:
    db_username: ""
    db_password: ""
    db_max_retries: 3
    db_schema_name: ""
  wynndb:
    db_username: ""
    db_password: ""
    db_max_retries: 3
    db_schema_name: ""
