application:
  debug: false
  admin_discord_id: 0

logging:
  discord_log_webhook: ""
  discord_status_webhook: ""

secret:
  discord:
    bot_token: ""
  fazbot:
    username: ""
    password: ""
    database_name: ""
    max_retries: 0
  wynndb:
    username: ""
    password: ""
    database_name: ""
    max_retries: 0
